// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Webapplication2.Database;

#nullable disable

namespace Webapplication2.Database.Migrations
{
    [DbContext(typeof(TodoDbContext))]
    [Migration("20230713065805_AuthorEntity")]
    partial class AuthorEntity
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("WebApplication2.Models.Todoo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Animal")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Due")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Todos");

                    b.HasData(
                        new
                        {
                            Id = 2,
                            Animal = 0,
                            Created = new DateTime(2023, 7, 13, 12, 28, 5, 189, DateTimeKind.Local).AddTicks(5425),
                            Description = " siriyawathi gana",
                            Due = new DateTime(2023, 7, 18, 12, 28, 5, 189, DateTimeKind.Local).AddTicks(5436),
                            Status = 2,
                            Title = "Apatath Dawasaka Ira Payado hichchi putheeee.... "
                        });
                });

            modelBuilder.Entity("WebApplication2.Models.Todoomommy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("number")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Todoomommies");

                    b.HasData(
                        new
                        {
                            Id = 3,
                            Description = "Hello Machan KOhomada IThin.....",
                            Name = "Vinuka Nvod",
                            number = 714703776
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
